var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(m,u,B){m instanceof String&&(m=String(m));for(var H=m.length,C=0;C<H;C++){var z=m[C];if(u.call(B,z,C,m))return{i:C,v:z}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(m,u,B){m!=Array.prototype&&m!=Object.prototype&&(m[u]=B.value)};
$jscomp.getGlobal=function(m){return"undefined"!=typeof window&&window===m?m:"undefined"!=typeof global&&null!=global?global:m};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(m,u,B,H){if(u){B=$jscomp.global;m=m.split(".");for(H=0;H<m.length-1;H++){var C=m[H];C in B||(B[C]={});B=B[C]}m=m[m.length-1];H=B[m];u=u(H);u!=H&&null!=u&&$jscomp.defineProperty(B,m,{configurable:!0,writable:!0,value:u})}};
$jscomp.polyfill("Array.prototype.find",function(m){return m?m:function(m,B){return $jscomp.findInternal(this,m,B).v}},"es6","es3");
(function(){function m(){var e=new fa;e.init();return e}function u(){this._intervalID=this._micLevelCallback=this._analyserNode=null}function B(){var e;this.onmessage=function(a){switch(a.data.command){case "init":e=f;e.init(a.data.config);this.postMessage({command:"ready"});break;case "record":e.record(a.data.buffer);break;case "getAudioData":a=e.getAudioData();this.postMessage({command:"audioBlob",audioBlob:a});break;case "reset":e.reset()}};var f=function(){function a(a,c,d){for(var b=0;b<d.length;b++)a.setUint8(c+
b,d.charCodeAt(b))}var c=[],d=0,e;return{init:function(a){e=a.sampleRate},record:function(a){c.push(a);d+=a.length},getAudioData:function(){for(var b=c,f=new Float32Array(d),h=0,l=0;l<b.length;l++)f.set(b[l],h),h+=b[l].length;b=new ArrayBuffer(44+2*f.length);b=new DataView(b);a(b,0,"RIFF");b.setUint32(4,32+2*f.length,!0);a(b,8,"WAVE");a(b,12,"fmt ");b.setUint32(16,16,!0);b.setUint16(20,1,!0);b.setUint16(22,1,!0);b.setUint32(24,e,!0);b.setUint32(28,2*e,!0);b.setUint16(32,2,!0);b.setUint16(34,16,!0);
a(b,36,"data");b.setUint32(40,2*f.length,!0);h=44;for(l=0;l<f.length;l++,h+=2){var g=Math.max(-1,Math.min(1,f[l]));b.setInt16(h,0>g?32768*g:32767*g,!0)}return new Blob([b],{type:"audio/wav"})},reset:function(){c=[];d=0}}}()}function H(){this._startTime=0;this.start=function(){this._startTime=(new Date).getTime()};this.duration=function(){return(new Date).getTime()-this._startTime}}function C(){a:{try{if(window.parent&&window.parent.speakpipeHtml5Recorder){var e=window.parent.speakpipeHtml5Recorder;
break a}}catch(d){}e=null}e||(e=m());var f=siteSettings,a=widgetTypeCode,c=clientTypeCode;O.init();z.init($,f);X.init(e,f,D);X.html5Recorder=e;oa.init($,f,X,a,c,D)}var z=function(){function e(){var a=k.siteTypeId,b=v.getParameterByName("rf");if(!b){if(1===a||4===a)b=document.referrer;b||(b=window.location.href)}return b}function f(b){b.speakpipe_id=k.siteId;b.speakpipe_public_token=k.publicToken;b.visitor_token=a();b.session_token=l;var c="";window.swfobject&&(c=swfobject.getFlashPlayerVersion(),
c=c.major+"."+c.minor+"."+c.release);b.flash_version=c;b.ref_url=e();return b}function a(){return v.readCookie("speakpipe_visitor")}function c(a,b,t){t&&(b=b+"="+encodeURIComponent(t),a=a?a+("&"+b):"?"+b);return a?a:""}function d(a,b){var t=location.protocol+"//"+location.hostname+(location.port?":"+location.port:"")+location.pathname;b=c(location.search,"rf",b);b=c(b,"mode",a);3===k.siteTypeId&&(b=c(b,"page_id",k.publicToken));return t+b}function h(a){return v.getParameterByName("rf")?d(a):d(a,e())}
function b(){var a=v.getParameterByName("rf");a||(a=document.referrer);return a}var n=null,k=null,l=null;return{init:function(b,c){n=b;k=c;b=c.visitorToken;a()||v.setCookie("speakpipe_visitor",b);l=v.randomString(16)},isInsideFrame:function(){try{return window.self!==window.top}catch(g){return!0}},isParentPageSecure:function(){var a=b();return a&&0==a.indexOf("https://")?!0:!1},isOnSpeakPipeCom:function(){var a=b();return a&&0==a.indexOf("https://www.speakpipe.com")?!0:!1},isLocalhost:function(){return"localhost"===
location.hostname||"127.0.0.1"===location.hostname},getAppURL:h,addEnvParams:f,postRequest:function(a,b,t,c){k&&(b.zact_value="fg43lj3454589lfg41560lgfh53034f4rrl5kg748fd43sg43sg435",b=f(b),n.ajax({url:a,type:"POST",data:b,dataType:"json",success:function(a){t&&t(a)},error:function(){c&&c()}}))},getVisitorToken:a,getLastMsgKey:function(a){return v.readCookie("site"+a+"_last_msg")},setLastMsgKey:function(a,b){v.setCookie("site"+a+"_last_msg",b)},reloadApp:function(){window.location.href=h();return!1},
log:function(){}}}(),O=function(){var e=null,f,a,c,d,h=null;return{init:function(){var b=document.getElementById("audio-player");b&&(b.onerror=function(a){},b.ontimeupdate=function(){f&&c&&c(b.currentTime)},b.onloadedmetadata=function(){d=b.duration;a&&a(d)},b.onended=function(){h&&h()})},play:function(b,d,k,l){a=l;c=d;h=k;f=!0;d=document.getElementById("audio-player");d.volume=1;e!==b&&(d.src=b,d.load(),e=b);d.play()},pause:function(){f=!1;var a=document.getElementById("audio-player");a&&(a.pause(),
h&&h())},getDuration:function(a,c,d){if(c){var b=new Audio;b.volume=0;b.muted=!0;var e=!1;b.oncanplay=function(){e||c(b.duration);e=!0};b.onerror=d;b.src=a;b.load();b.currentTime=86400}}}}(),pa=function(){function e(a){switch(a.data.command){case "audioBlob":r=a.data.audioBlob;I&&I();break;case "ready":l=!0}}function f(){return d.context.sampleRate}function a(a){g&&(t=!0,a=a.inputBuffer.getChannelData(0),w+=a.length,k.postMessage({command:"record",buffer:a}))}var c=null,d,h,b,n,k,l=!1,g=!1,r=null,
t=!1,I=null,w=0;return{init:function(){},createAudioContext:function(){c||(c=new AudioContext,n=new u,h=n.createAnalyser(c),b=c.createScriptProcessor(0,1,1),b.onaudioprocess=a,h.connect(b),b.connect(c.destination),c.onstatechange=function(){g&&"running"!=c.state&&D.info("audiocontext_statechange","state: "+c.state)})},initRecording:function(a){d=c.createMediaStreamSource(a);d.connect(h);k||(a=new Blob(["("+B.toString()+")();"],{type:"application/javascript"}),a=(window.URL||window.webkitURL).createObjectURL(a),
k=new Worker(a),k.onmessage=e,k.postMessage({command:"init",audioType:"wav",config:{sampleRate:f(),mp3BitRate:128}}))},isRecording:function(){return g},isAudioReady:function(){return null!==r},isDataStarted:function(){return t},start:function(a){t=!1;g=!0;n.startUpdate(a)},stop:function(a){I=a;g&&(g=!1,n.stopUpdate(),k.postMessage({command:"getAudioData"}))},reset:function(){g=!1;r=null;w=0;n.stopUpdate();k.postMessage({command:"reset"});t=!1},getSampleRate:f,getMimeType:function(){return"audio/wav"},
getAudioBlob:function(){return r},isWorkerReady:function(){return l},getCalculatedDuration:function(){var a=f();return a&&0<a?w/a:0}}}(),qa=function(){function e(){0>a.retryCount?f():a.errorCallback&&a.errorCallback.apply(this,arguments)}function f(){d&&d();a.retryCount+=1;a.func(a.params,a.successCallback,e)}var a=null,c=null,d=null;this.init=function(a,b){c=a;d=b};this.execute=function(d,b,f,k){a={func:d,params:b,retryCount:0,successCallback:f,errorCallback:null};a.errorCallback=k?k:c;a.func(a.params,
a.successCallback,e)};this.retry=f},ra=function(){function e(f,a,c,d){d||(d=0);$.post(f,function(h){h&&h.status?"pending"===h.status?setTimeout(function(){d+=1;3>=d?e(f,a,c,d):c&&c()},4E3):"sent"===h.status&&a?a(h):c&&c():c&&c()},"json")}return{process:function(f,a){if(f){var c="/api/last-msg-info/"+z.getVisitorToken();e(c,f,a)}}}}();(function(){function e(){return swfobject.getObjectById("_speakpipe_flash_recorder")}function f(){e().stopRecord();g=!1}function a(){e().stopPlayback()}function c(a,
b,c){for(var t=0;t<a.length;t++){var d=a[t];if(d.name===b)return d.value}if(c)return c;throw'Cannot find the parameter "'+b+'".';}function d(a){return!v.strContains(a,"s3.amazonaws.com",!0)}function h(a,t,f){var h=c(t,"key","audio-recording.bin"),I=c(t,"Content-Type","audio/mpeg");x.info("start_speedtest");sa.start(function(c,f){e().generateTestData(c);F=f;e().uploadTestData(h,I,b,d(a),t)},function(a){f&&f(a)})}var b,n,k=!1,l=null,g=!1,r=null,t=null,I=null,w=null,P=null,m=null,E=null,q=null,F=null,
y=null,ha=null,x=null,u=null;window._speakpipe={microphone_recorder_events:function(a,b,c){switch(a){case "flash_loaded":k=!0;l&&l();break;case "microphone_allowed":r&&r();break;case "microphone_denied":t&&t();break;case "mic_handler_active":I&&I();break;case "microphone_activity_level":w&&w(b);break;case "mp3_encode_progress":P&&P(Math.round(b/c*100));break;case "mp3_encode_completed":m&&m();break;case "sound_progress":E&&E(b);break;case "sound_stop":q&&q();break;case "test_data_upload_complete":F&&
F();break;case "upload_complete":Z.complete();y(b);break;case "upload_error":ha&&ha();x.error("upload_error",b);break;case "flash_error":x.error("flash_error",b)}}};return{init:function(a,c,t,d,f){u=a+"/";x=f;b=c;n=t},getRecorderName:function(){return"flash-recorder"},isAvailable:function(){return!1},isReady:function(){return k},ready:function(a){k?a&&a():l=a},getInitError:function(){return{title:"",text:""}},requestMicrophone:function(a,b){r=a;t=b;setTimeout(function(){var a=e().initMicrophone();
k=!0;a="codec: "+a+"; mic_count: "+e().getMicrophoneCount();x.info("mic_request",a)},300)},isMicAllowed:function(){return k?e().isMicrophoneAllowed():!1},isRecording:function(){return g},isDataStarted:function(){return!0},getActualDuration:function(){return null},startRecord:function(a,c){try{I=a,w=c,e().startRecord(600,"mp3",b,n,u),g=!0}catch(Q){alert(Q)}},stopRecord:f,resetRecord:function(){f();a()},encodeAudio:function(a,b){P=a;m=b;e().showMP3Progress(!0);e().convertToMP3()},playAudio:function(a,
b){E=a;q=b;e().playRecord()},stopPlayingAudio:a,isAmazonUpload:function(){return!0},uploadAudio:function(a,t,f,I,g,l){ha=g;h(a,l,function(h){f&&f(0);y=I;var g=c(t,"key","audio-recording.bin"),l=c(t,"Content-Type","audio/mpeg"),k=e().prepareAudioData();h&&Z.start(k/(h-.15*h),f);d(a)||x.info("start_amazon_upload","est_speed: "+Math.round(h)+" B/ms");e().uploadRecord(g,l,b,d(a),t)})},updateMsgParams:function(a){a.size_bytes=e().prepareAudioData()}}})();var U=function(){return{uploadFormData:function(e,
f,a,c,d){$.ajax({type:"POST",url:f,data:e,dataType:"json",processData:!1,contentType:!1,xhr:function(){var c=$.ajaxSettings.xhr();c&&c.upload.addEventListener("progress",function(b){b.lengthComputable&&(b=b.loaded/b.total*100,a&&a(b))},!1);return c}}).done(function(a){c&&c(a)}).fail(function(a,b,c){d&&d(a.status,b,c)})},isValidAudioFile:function(e){},appendParamsToFormData:function(e,f){for(var a=0;a<f.length;a++){var c=f[a];e.append(c.name,c.value)}}}}();window.createHtml5Recorder=m;var fa=function(){function e(a){b=
a;l=!0;try{g.initRecording(a)}catch(I){D.error("js_error","_rec.initRecording error: "+I.message)}null!=k&&k()}function f(){if(b)for(var a=b.getTracks(),c=0;c<a.length;c++)if(a[c].muted)return!0;return!1}function a(){return g.isDataStarted()}function c(){n=null;g.reset();r=null;V.reset()}function d(){var a=g.getAudioBlob();return a?(n||(n=(window.URL||window.webkitURL).createObjectURL(a)),n):null}function h(){var a=g.getAudioBlob();return a?a.size:null}var b,n,k,l=!1,g,r=null;return{init:function(){window.AudioContext=
window.AudioContext||window.webkitAudioContext;N.isSupported()?g=N:(g=pa,g.init());V.init(g)},onUserGesture:function(){g.createAudioContext()},getRecorderName:function(){return"html5-recorder"},isAvailable:function(){return!!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia||navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia)&&!!window.AudioContext&&!!window.Worker},needPopup:function(){return z.isInsideFrame()&&!z.isParentPageSecure()&&
!z.isLocalhost()},needPopupIfDenied:function(){return z.isInsideFrame()&&!z.isOnSpeakPipeCom()},isReady:function(){return!0},ready:function(a){a&&a()},getInitError:function(){return{title:"",text:""}},getAudioInputCount:function(a){try{if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var b=0;navigator.mediaDevices.enumerateDevices().then(function(c){c.forEach(function(a){"audioinput"==a.kind&&b++});a&&a(b)}).catch(function(b){a&&a(b)})}}catch(w){a&&a(w)}},getAudioBlobSize:h,getSampleRate:function(){return g.getSampleRate()},
getMimeType:function(){return g.getMimeType()},requestMicrophone:function(a,b,c){k=a;a={audio:!0};navigator.mediaDevices&&navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia(a).then(e).catch(function(a){b&&b();if(a){if("NotAllowedError"!==a.name&&"PermissionDeniedError"!==a.name){var c=a;a.name&&(c="err.name: "+a.name+"; "+a);D.error("gum_error",c)}}else D.error("gum_error","Unknown error")}):(navigator.getUserMedia=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||
navigator.msGetUserMedia,navigator.getUserMedia?navigator.getUserMedia({audio:!0},e,b):D.error("old_gum_error"))},isMicAllowed:function(){return l},isMuted:f,isRecording:function(){return g.isRecording()},isDataStarted:a,startRecord:function(a,b){c();g.start(b);a&&a()},stopRecord:function(a){g.stop(function(){var b=d(),c=h();b&&0<c?O.getDuration(b,function(b){r=b;a&&a(b)},function(){D.error("getduration_error","blob_size: "+c)}):(a&&a(null),D.info("audio_ready","blob_size: "+c))})},resetRecord:c,
playAudio:function(a,b){var c=d();c?O.play(c,a,b):(a="audioUrl is null; isAudioReady: "+g.isAudioReady(),D.info("play_record_error",a))},stopPlayingAudio:function(){O.pause()},isAmazonUpload:function(){return!1},uploadAudio:function(a,b,c,d,f){var t=g.getAudioBlob();if(t){var e=new FormData;U.appendParamsToFormData(e,b);e.append("file",t,"test_audio.wav");U.uploadFormData(e,a,c,d,f)}else D.error("upload_error","audioBlob is null; isAudioReady: "+g.isAudioReady())},updateMsgParams:function(a){},getRecorderInfoStr:function(){var a=
"sampleRate: "+g.getSampleRate();a+="; MediaRecorder: "+(g==N?"yes":"no");g==N&&(a+="; mimeType: "+g.getMimeType());return a},getRecorderStateStr:function(){var c="is_muted: "+f();if(b){c+="; mediaStream.active: "+b.active;var d=b.getTracks();1!==d.length?c+="; tracks: "+d.length:(d=d[0],c+="; track.readyState: "+d.readyState,c+="; track.enabled: "+d.enabled);c+="; "}return c+="data_started: "+a()},getDurationInfoStr:function(a){var b="",c=r;c&&(c=Math.round(c));var d=g.getCalculatedDuration();b+=
"duration: "+Math.round(a);b+="; actual_duration: "+c;d&&(d=Math.round(d),b+="; calc_duration: "+d);return b},isRecordingProcessValid:function(a){return V.isRecordingProcessValid(a,r)},getRecordingProcessError:function(a){return V.getRecordingProcessError(a,r)}}},A=function(){function e(c){h(c.id);var d=a(c.id);b(c.id);return d}function f(a){for(var b=0;b<r.length;b++)if(r[b].key===a)return r[b];return null}function a(a){a=c(a);return v.trimStr(a.val())}function c(a){return g("#"+a)}function d(a){for(var b=
0;b<r.length;b++)if(r[b].id===a)return r[b].placeholder;return null}function h(b){var f=c(b),e=d(b);0<f.length&&a(b).toLowerCase()==e.toLowerCase()&&f.val("")}function b(b){var f=d(b),e=c(b);0<e.length&&f&&(b=a(b),e.attr("placeholder",f),""===b&&e.val(f))}function n(a){var b=c(a);0<b.length&&b.keypress(function(){b.removeClass("value-error")})}function k(a){var d=c(a);0<d.length&&(d.focus(function(){h(a)}).blur(function(){b(a)}).blur(),n(a))}function l(a){var b="optional";a.required&&(b="required");
a.placeholder=a.text+" ("+b+")"}var g=null,r=null;return{init:function(a,b){g=a;r=[{key:"authorName",id:"-speakpipe-record-author-name",text:"Your name",required:b.dialog.nameRequired},{key:"authorEmail",id:"-speakpipe-record-author-email",text:"Your email",required:b.dialog.emailRequired,validator:"email"},{key:"recipientEmail",id:"-speakpipe-recipient-email",text:"Recipient's email",required:!0,validator:"email"},{key:"msgTitle",id:"-speakpipe-recording-title",text:"Recording title",required:!1}];
for(a=0;a<r.length;a++)b=r[a],l(b),k(b.id)},getValidated:function(){for(var a={},b=!0,d=0;d<arguments.length;d++){var h=arguments[d],g=f(h),l=g,k=e(l),n=!0;l.required&&(k&&0!==k.length||(n=!1));if(n&&k&&l.validator)switch(l.validator){case "email":n=/^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/.test(k)}n?b&&(a[h]=e(g)):(b=!1,a=null,c(g.id).addClass("value-error"))}return a},setFieldRequired:function(a,
c){if(a=f(a))a.required=c;h(a.id);l(a);b(a.id)},setFieldValue:function(a,b){(a=f(a))&&b&&c(a.id).val(b)},setFieldEnabled:function(a,b){(a=f(a))&&c(a.id).prop("disabled",!b)},reset:function(){for(var a=0;a<r.length;a++)c(r[a].id).removeClass("value-error")}}}(),N=function(){function e(a){b()&&(a=a.inputBuffer.getChannelData(0),q+=a.length)}function f(){for(var a=["audio/ogg","audio/webm","audio/mp4"],b=a.length,c=0;c<b;c++){var d=a[c],f=window.MediaRecorder;if(f&&f.isTypeSupported&&f.isTypeSupported(d))return d}return null}
function a(a){l.push(a.data);b()?F&&(a=new Blob(l,{type:k}),F(a),F=null):(z=!0,P&&P())}function c(a){P=a;b()&&(g.stopUpdate(),n.stop())}function d(){c();l=[];P=E=null;z=!1;q=0}function h(){return t.context.sampleRate}function b(){return n?"recording"===n.state:!1}var n,k,l=[],g,r=null,t,m,w,P=null,z=!1,E=null,q=0,F=null;return{createAudioContext:function(){r||(r=new AudioContext,g=new u,m=g.createAnalyser(r),w=r.createScriptProcessor(0,1,1),w.onaudioprocess=e,m.connect(w),w.connect(r.destination),
r.onstatechange=function(){b()&&"running"!=r.state&&D.info("audiocontext_statechange","state: "+r.state)})},initRecording:function(b){t=r.createMediaStreamSource(b);t.connect(m);k=f();n=new MediaRecorder(b,{mimeType:k});n.ondataavailable=a},start:function(a){d();n.start();g.startUpdate(a)},stop:c,reset:d,isRecording:b,isAudioReady:function(){return z},isDataStarted:function(){return!0},getSampleRate:h,getMimeType:function(){return n.mimeType},getAudioBlob:function(){return z?(E||(E=new Blob(l,{type:k})),
E):null},isSupported:function(){if(v.checkUA("firefox/87"))return!1;var a=f();return!!window.MediaRecorder&&!!a},requestData:function(a){n&&n.requestData&&(F=a,n.requestData())},getDataSize:function(){for(var a=0,b=0;b<l.length;b++)a+=l[b].size;return a},getCalculatedDuration:function(){var a=h();return a&&0<a?q/a:0}}}();u.prototype.createAnalyser=function(e){this._analyserNode=e.createAnalyser();this._analyserNode.fftSize=1024;this._analyserNode.smoothingTimeConstant=.5;return this._analyserNode};
u.prototype.startUpdate=function(e){if(this._micLevelCallback=e)this._intervalID=setInterval(this._onUpdate.bind(this),70)};u.prototype.stopUpdate=function(){this._intervalID&&(clearInterval(this._intervalID),this._intervalID=null)};u.prototype._onUpdate=function(){this._micLevelCallback&&this._calcMicLevel(this._micLevelCallback)};u.prototype._calcMicLevel=function(e){var f=this._analyserNode.frequencyBinCount,a=new Uint8Array(f);this._analyserNode.getByteFrequencyData(a);for(var c,d=0,h=0,b=0;b<
f;b++)c=a[b],0<c&&(d+=c*c,h++);f=0;0<h&&(d=Math.sqrt(d/h),f=d/255*100);e(f,a);return f};var ba=function(){var e=null,f=null;return{isLevelFreezed:function(a){return f&&a?7<a-f:!1},onMicLevel:function(a,c){e===a?f||(f=c):(f=null,e=a)},reset:function(){f=e=null}}}(),la=function(){function e(a){for(var b=0,c=0;c<a.length;c++)b+=a[c];return b/a.length}function f(a,b){a=a.slice(0,a.length/4);for(var c=Math.floor(a.length/b),d=[],f,g=0;g<b;g++)f=g*c+c,f=a.slice(g*c,f),d.push(e(f)/210);return d}function a(a,
b,c,d){if(0<Math.abs(d)){var f=0;1.5>Math.abs(d)/7&&(f=2);d=c-d;var e=b+3.5,h=b+7;a.beginPath();a.lineWidth=.5;a.moveTo(b,c);a.quadraticCurveTo(b+f,d,e,d);a.quadraticCurveTo(h-f,d,h,c);a.stroke();return h}}var c=null,d=null;return{init:function(){(c=document.getElementById("rec-wave"))&&(d=c.getContext("2d"))},visualize:function(e){if(e){e.sort(function(a,b){return b-a});var b=c.width/2,h=c.height/2,k=f(e,Math.floor(b/7));d.clearRect(0,0,c.width,c.height);d.beginPath();d.lineWidth=.1;d.stroke();d.lineWidth=
1;e=[];for(var l=0;l<k.length;l++){var g=Math.round(k[l]*h);g>h&&(g=h);e.push(g)}k=b-7;g=!1;for(l=0;l<e.length;l++)g?(a(d,k,h,e[l]),a(d,b,h,-e[l])):(a(d,k,h,-e[l]),a(d,b,h,e[l])),b+=7,k-=7,g=!g}}}}(),Z=function(){function e(){98>f?(f++,c&&c(Math.round(f))):a&&(clearInterval(a),a=null)}var f=0,a=null,c=null;return{start:function(d,h){c=h;f=0;c&&c(0);a=setInterval(e,Math.round(d/100))},complete:function(){a&&(clearInterval(a),a=null);c&&c(100)}}}(),X=function(){function e(a){if(M[a]){var b=Array.prototype.slice.call(arguments);
b=b.slice(1);M[a].apply(this,b)}}function f(){A=setInterval(function(){x++;e("recDuration",x);q.isRecordingProcessValid(x)?10<x&&0>=c()?g():x>=F.maxDuration&&g():g()},1E3)}function a(a,b){B+=a;C++;ba.onMicLevel(a,x);e("micLevel",a,b)}function c(){return 0<C?(B/C).toFixed(2):0}function d(){D=!0;f();e("recStarted")}function h(){e("recInit");D=!1;C=B=x=0;q.startRecord(d,a);y.info("start_record",q.getRecorderInfoStr());setTimeout(b,700)}function b(){D||(e("recNotActive"),y.error("mic_handler_problem"))}
function n(){y.error("stream_muted","duration: "+x)}function k(){var a=new H;a.start();q.requestMicrophone(h,function(){var b=a.duration(),c=500>b?"browser_denied":"user_denied";e("micDenied",q.getRecorderName(),c);y.error("mic_denied","reason: "+c+"; deny_time: "+b+" ms; audioinput_count: "+T)},n)}function l(a){q.isRecording()&&(q.stopRecord(a),clearInterval(A),A=null,e("recDuration",x))}function g(){q.isRecording()?l(function(){r()&&e("audioReady");var a=q.getAudioBlobSize(),b="avg_level: "+c();
b+="; "+q.getDurationInfoStr(x);b+="; audioinput_count: "+T;b=b+("; blob_size: "+a)+("; data_started: "+q.isDataStarted());q.isMuted()&&(b+="; muted: true");y.info("stop_record",b)}):q.isMicAllowed()&&y.error("stop_error","recording already stopped");return!1}function r(){var a;if(a=q.getRecordingProcessError(x))switch(a){case "data_not_started":return e("audioValidationResult","recording_error"),a=q.getRecorderStateStr(),y.error("recording_error",a),!1;case "data_empty":return e("audioValidationResult",
"recording_error"),a="duration: "+x,a+="; "+q.getRecorderStateStr(),y.error("blob_empty_error",a),!1;case "duration_error":return e("audioValidationResult","audio_error"),a=q.getDurationInfoStr(x),a+="; "+q.getRecorderStateStr(),y.error("duration_error",a),!1}return 0>=c()?(e("audioValidationResult","no_sound_error"),!1):!0}function t(){Q=!0;e("playStarted");try{q.playAudio(function(a){e("playDuration",a,x)},m)}catch(ta){var a=ta.message;a=a+"; blobSize: "+q.getAudioBlobSize();y.error("play_audio_error",
a)}return!1}function m(){Q=!1;e("playStopped")}function w(){q&&q.stopPlayingAudio();return!1}function v(a){var b={};z.addEnvParams(b);b.audio_format=F.audioFormat;b.duration=x;b.avg_mic_level=c();b.mime_type=q.getMimeType?q.getMimeType():null;b.author_name=a.authorName;a.authorEmail&&(b.author_email=a.authorEmail);a.parentMsgId&&(b.parent_audio_id=a.parentMsgId);a.toEmail?b.to_email=a.toEmail:a.recipientEmail&&(b.to_email=a.recipientEmail);a.recordingTypeCode&&(b.recording_type_code=a.recordingTypeCode);
a.msgTitle&&(b.msg_title=a.msgTitle);b.zact_value="fg43lj3454589lfg41560lgfh53034f4rrl5kg748fd43sg43sg435";return b}function u(){e("deliveryStatus","init");ra.process(function(a){e("deliveryStatus","complete",a);y.info("delivery_completed")},function(){e("deliveryStatus","error");var a=!1;M.deliveryStatus&&(a=!0);y.error("delivery_error","deliveryStatus: "+a)})}function E(a,b){if(b){var c=function(){e("uploadStatus","init")},d=function(){e("uploadStatus","start")},f=function(a){e("uploadStatus","complete",
a);a&&a.audioReady||M.deliveryStatus&&u()},g=function(b,c,d){e("uploadStatus","error");b="status: "+b+"; textStatus: "+c+"; errorThrown: "+d+"; blobSize: "+a.getAudioBlobSize();y.error("upload_error",b)};b=v(b);W.init(F.domain,F.isProduction);try{W.uploadAudio(a,b,c,d,M.uploadProgress,f,g)}catch(ca){c=ca.message,c=c+"; blobSize: "+a.getAudioBlobSize(),y.error("unexpected_upload_error",c)}}}var q=null,F=null,y=null,A=null,x=0,B=0,C=0,D=!1,Q=!1,T,M={micDenied:null,micLevel:null,recDuration:null,playDuration:null,
playStarted:null,playStopped:null,recInit:null,recNotActive:null,recStarted:null,encodeStart:null,encodeProgress:null,audioValidationResult:null,audioReady:null,uploadStatus:null,uploadProgress:null,deliveryStatus:null,flashObjectError:null};return{init:function(a,b,c){q=a;F=b;y=c;a&&a.getAudioInputCount&&a.getAudioInputCount(function(a){T=a})},setEventHandler:function(a,b){M[a]=b},isMicAllowed:function(){return q.isMicAllowed()},startRecord:function(){e("recDuration",0);e("micLevel",0);e("encodeProgress",
0);if(q.isAvailable()){if(q.onUserGesture)q.onUserGesture();q.isMicAllowed()?h():(e("beforeMicRequest",q.getRecorderName(),q.isReady()),q.ready(function(){k()}))}else e("flashObjectError"),y.error("flash_not_loaded");return!1},stopRecord:g,resetRecord:function(){l();w();q.resetRecord();ba.reset();return!1},togglePlayingAudio:function(a){Q?w():t();a&&a(Q)},playAudio:t,stopPlayingAudio:w,sendRecording:function(a){w();E(q,a)},sendAudioFile:function(a,b){E({uploadAudio:function(b,c,d,f,e){var g=new FormData;
U.appendParamsToFormData(g,c);g.append("file",a);U.uploadFormData(g,b,d,f,e)},isAmazonUpload:function(){return!1}},b)},retrySending:function(){W.retryUpload();y.info("retry_upload")},retryDelivery:function(){u();y.info("retry_delivery")},reloadApp:function(){y.info("reload_widget","parent: "+$(this).closest(".dlg-page").attr("id"));z.reloadApp()}}}(),D=function(){function e(f,a,c){"js_error"===a&&v.strContains(c,"Permission denied to access property",!0)||(f={action_code:a},c&&(f.log_message=c),z.postRequest("/widget_log",
f))}return{error:function(f,a){e("error",f,a)},warn:function(f,a){e("warn",f,a)},info:function(f,a){e("info",f,a)},debug:function(f,a){e("debug",f,a)}}}(),oa=function(){function e(a,b){function c(a,b,c,d,J){a.css("left",b+"px");a.css("top",c+"px");a.css("width",d+"px");a.css("height",J+"px")}var d=f(a);d&&(a="#"+a+"-page",d=$("#"+d),b?($(".widget-powered-by").addClass("nativeobj-flag"),b=$(a).find(".nativeobj-container"),a=b.offset(),c(d,a.left,a.top,b.outerWidth(),b.outerHeight())):(c(d,0,0,1,1),
$(".widget-powered-by").removeClass("nativeobj-flag")))}function f(a){var b=null;switch(a){case "flashobj":b="_speakpipe_flash_recorder";break;case "silverlightobj":b="silverlight-plugin"}return b}function a(a,b){"flashobj"===a&&(a=$("#"+a+"-page .run-obj-hint"),b?a.hide():a.show())}function c(b,c){switch(b){case "flash-recorder":var J="flashobj";break;case "silverlight-recorder":J="silverlightobj"}J?(d(J,!0),a(J,c),setTimeout(function(){e(J,!0)},1)):"html5-recorder"===b&&(v.isBrowser("firefox")?
d("firefox-mic-permission"):v.isBrowser("chrome")?d("chrome-mic-permission"):d("generic-mic-permission"))}function d(a){Y&&(e(Y,!1),p("#"+Y+"-page").hide());var b=null;a&&(b=p("#"+a+"-page"),b.show(),da=Y,Y=a);return b}function h(a,b){var c=p("#progress-page");c.find(".widget-page-title").text(a);a=c.find(".fake-indicator");c=c.find(".progressbar");b?(a.show(),c.hide()):(a.hide(),c.show());d("progress")}function b(a){a=k(a);p(".recording-duration").html(a);p(".wgt-audio-duration").html(a);p("#-speakpipe-send-msg-duration").html(a)}
function n(a,b){var c=p("#mic-activity-level"),d=100-a;c.find(".mic-al-left div").css("width",d+"%");c.find(".mic-al-right div").css("width",a+"%");la.visualize(b)}function k(a){var b=Math.floor(a/60);a=Math.floor(a-60*b);10>b&&(b="0"+b);10>a&&(a="0"+a);return b+":"+a}function l(a,b){p("#play-recording-page .playing-time").text(k(a));a>b&&(a=b);a=a/b*100;p(".wgt-audio-player .wgt-seek-bar .wgt-played").css("width",a+"%")}function g(a){a=Math.round(a);var b=p("#progress-page .progressbar div"),c=p("#progress-page .progressbar span");
a+="%";b.css("width",a);c.text(a)}function r(a){g(a)}function t(a){g(a)}function m(a,b,c){b=a.fromUser;var d=!0;c?A.setFieldValue("authorEmail",""):b&&b.email&&(A.setFieldValue("authorEmail",b.email),d=!a.toEmail,b.name&&A.setFieldValue("authorName",b.name));A.setFieldEnabled("authorEmail",d)}function w(a,b,c,f){function e(){p("#recording-warn-page").find(".dlg-action").find("a").hide()}var J=p("#recording-warn-page");c?(e(),J.find(".bt-reset-record").show()):(J.find(".dlg-action").find("a").show(),
J.find(".bt-reset-record").hide());f&&e();J.find(".widget-page-title").html(a);J.find(".dlg-msg").html(b);d("recording-warn",!0)}function u(a){var b=null;switch(a){case "ios":ea.isAvailable()||(v.isiOS11()?(b="open-safari",v.isInAppBrowser()&&$("#open-safari-page .open-safari-hint").show(),z.isInsideFrame()&&!z.isParentPageSecure()&&(b=null)):b="ios11-required")}return b}function B(){L.stopPlayingAudio();d("send-recording");return!1}function E(a,b){a=ua.get(a);b&&(a+=" "+b);return a}function q(a){var b=
$("#recording-warn-page .skip-replay-btn"),c=$("#recording-warn-page .rc-play-rec"),d=$("#recording-warn-page .rc-reload-widget");c.show();b.show();switch(a){case "no_sound_error":c.hide();b.hide();d.show();w(E("no_sound_from_mic"),E("no_sound_error"),!0);break;case "too_quiet_warn":d.hide();w(E("listen_your_msg"),E("too_quiet_warn"));break;case "listen_msg_warn":d.hide();w(E("listen_your_msg"),E("listen_msg_warn"));break;case "recording_error":c.hide();b.hide();d.show();w("Recording error","There was an unexpected error with the recording. Please try again.",
!0);break;case "audio_error":c.hide(),b.hide(),d.show(),w("Recording error","There was an unexpected error with the recording. Please try again.",!0)}}function F(a,b){switch(a){case "init":h("Start sending...",!0);g(0);break;case "start":h("Uploading the audio...");break;case "complete":ma?b&&b.audioReady&&(O(b),d("rec-details")):d("thankyou",!0);break;case "error":d("upload-error",!0)}}function y(a,b){switch(a){case "init":h("Processing your recording on the server...",!0);break;case "complete":O(b);
d("rec-details");break;case "error":d("delivery-error")}}function C(a){(ma="free_recorder"===K||"outbox_widget"===K&&"library_rec"===a)?L.setEventHandler("deliveryStatus",y):L.setEventHandler("deliveryStatus",null)}function x(a,b){"browser_denied"===b?"html5-recorder"===a&&ea.needPopupIfDenied()?d("open-popup"):d("mic-browser-denied"):d("mic-user-denied")}function D(){var a="send-recording";"free_recorder"===K&&(a="play-recording");d(a);setTimeout(function(){ia=!0},1E3)}function H(a){var b=G;A.reset();
var c=!1;"sent_rec"===a?($("#-speakpipe-recording-title").hide(),$("#-speakpipe-recipient-email").show(),$("#-speakpipe-record-author-email").show(),A.setFieldRequired("authorName",!0),A.setFieldRequired("authorEmail",!0),A.setFieldRequired("recipientEmail",!0)):"library_rec"===a?($("#-speakpipe-recording-title").show(),$("#-speakpipe-recipient-email").hide(),$("#-speakpipe-record-author-email").hide(),A.setFieldRequired("recipientEmail",!1),A.setFieldRequired("msgTitle",!1),A.setFieldRequired("authorName",
!1),A.setFieldRequired("authorEmail",!1),c=!0):(A.setFieldRequired("authorName",b.dialog.nameRequired),A.setFieldRequired("authorEmail",b.dialog.emailRequired));m(b,!0,c)}function O(a){var b=$("#rec-details-page .wgt-audio-player");b.attr("data-msg-id",a.audio_id);b.attr("data-src",a.audio_url);$("#rec-details-page .msg-url").val(a.msg_page_url);$("#rec-details-page .msg-link").attr("href",a.msg_page_url);$("#rec-details-page .btn-t1").attr("href",a.twitter_share);$("#rec-details-page .btn-f1").attr("href",
a.facebook_share);$("#rec-details-page .btn-g1").attr("href",a.googleplus_share);$("#rec-details-page .btn-b1").attr("href",a.buffer_share);$("#embed-recording-page .msg-embed-code").val(a.msg_embed_code);$("#rec-details-page .rec-embed-frame").attr("src",a.msg_embed_url)}function Q(a,b){b&&$.ajax({url:"/api/subscribe-email",type:"POST",data:{site_id:G.siteId,public_token:G.publicToken,name:a,email:b},dataType:"json",success:function(){R.info("email_subscribed")}})}function T(a){var b=(ja=a)?"Cancel":
"Reset",c=p("#send-recording-page .rc-play-rec");a?c.hide():c.show();p("#send-recording-page .rc-reset-rec").text(b)}function M(){var a=G,b;if(b="sent_rec"===a.recordingTypeCode?A.getValidated("authorName","authorEmail","recipientEmail"):"library_rec"===a.recordingTypeCode?A.getValidated("authorName","msgTitle"):A.getValidated("authorName","authorEmail"))a.parentMsgId&&(b.parentMsgId=a.parentMsgId),a.toEmail&&(b.toEmail=a.toEmail),a.recordingTypeCode&&(b.recordingTypeCode=a.recordingTypeCode);ia?
b&&(ja?(a=document.getElementById("audio-file-upload-input").files[0],L.sendAudioFile(a,b)):L.sendRecording(b),a=$("#subscribe-email-checkbox").is(":checked"),(!G.fromUser||!G.fromUser.isSiteOwner)&&b.authorEmail&&G.optin.enabled&&a&&Q(b.authorName,b.authorEmail)):L.isMicAllowed()&&R.info("send_btn_timeout")}function N(a){var b=p(".wgt-audio-player .wgt-play-pause-btn");a?(b.removeClass("wgt-play-icon"),b.addClass("wgt-pause-icon")):(b.removeClass("wgt-pause-icon"),b.addClass("wgt-play-icon"))}function U(a){a=
a.target.files[0];var b="You've selected an invalid file. Only audio files are allowed.";a&&v.strStartsWith(a.type,"audio")&&(7E7>=a.size?(T(!0),d("send-recording"),R.info("file_selected"),b=null):b="Selected file is too big. Please ensure your audio is under 70MB.");b&&alert(b)}function V(){da&&(d(da),da=null)}function X(){ja||L.resetRecord();d(S);return ia=!1}function aa(){var a=u(na);a?d(a):(a=$("#flashobj-page").outerWidth(),a=Math.round((a-220)/2),$("#flashobj-page .nativeobj-container").css("margin-left",
a+"px"),T(!1),L.startRecord())}function W(a,b,c){G.recordingTypeCode=a;C(a);H(a);"library_rec"===a?($(".send-email-hint").show(),$(".reset-rec-btn").show(),$(".cancel-email-btn").hide()):($(".send-email-hint").hide(),$(".reset-rec-btn").hide(),$(".cancel-email-btn").show());$("#send-recording-page .widget-page-title").text(b);$("#send-recording-page .send-rec-btn span").text(c)}function ca(a){G.isDemo?d("signup-notice"):a()}function Z(){p(".send-email-btn").click(function(){ca(function(){W("sent_rec",
"Send to email","Send")})});p(".cancel-email-btn").click(function(){W("library_rec","Save to library","Save")});p(".embed-rec-btn").click(function(){ca(function(){d("embed-recording")})})}function ba(a){a.setEventHandler("beforeMicRequest",c);a.setEventHandler("micLevel",n);a.setEventHandler("recDuration",b);a.setEventHandler("playDuration",l);a.setEventHandler("playStarted",function(){N(!0)});a.setEventHandler("playStopped",function(){N(!1)});a.setEventHandler("encodeStart",function(){h("Processing the audio...")});
a.setEventHandler("encodeProgress",r);a.setEventHandler("micDenied",x);a.setEventHandler("recInit",function(){d("recording")});a.setEventHandler("recStarted",function(){d("recording")});a.setEventHandler("recNotActive",function(){d("chrome-mic-extra-permission")});a.setEventHandler("audioReady",D);a.setEventHandler("uploadStatus",F);a.setEventHandler("uploadProgress",t);a.setEventHandler("audioValidationResult",q);a.setEventHandler("flashObjectError",function(){d("recorder-error").find(".dlg-msg").html("<p>Your browser is outdated and doesn't support audio recording.</p><p>Please install the latest version of Chrome, Firefox, Edge or Safari.</p>")});
Z()}function ka(){R.info("show_popup");var a=z.getAppURL("standalone");a=window.open(a,"SpeakPipe","toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width=500, height=600, top="+(screen.height/2-300)+", left="+(screen.width/2-250));window.focus&&a.focus();return!1}function fa(a){function b(){L.stopPlayingAudio();d("reset-recording")}a&&(L=a,ea.needPopup()?(p(".rc-start-rec").click(ka),p(".start-rec-btn").click(ka)):(p(".rc-start-rec").click(aa),
p(".start-rec-btn").click(aa)),p(".open-popup-btn").click(ka),p("#rc-stop-rec").click(a.stopRecord),p(".stop-rec-btn").click(a.stopRecord),p(".rc-play-rec").click(function(){d("play-recording");L.playAudio();return!1}),p(".confirm-reset-btn").click(X),p(".rc-reset-rec").click(b),p(".reset-rec-btn").click(b),p(".skip-replay-btn").click(D),p(".back-btn").click(V),p(".rc-show-send-page").click(B),p(".wgt-audio-player .wgt-play-pause-btn").click(function(){a.togglePlayingAudio(function(a){N(a)})}),p("#rc-send-msg").click(M),
p(".send-rec-btn").click(M),p(".btn-retry-sending").click(a.retrySending),p(".btn-retry-delivery").click(a.retryDelivery),p(".rc-reload-widget").click(a.reloadApp),p(".reload-widget-btn").click(a.reloadApp),ba(a));$("#audio-file-upload-input").change(U);p(".launch-ios-app-btn").click(function(){d("launch-ios-app")});p(".download-ios-app-btn").click(function(){d("download-ios-app")});p(".ios-cancel-btn").click(function(){d("ios-app")});p(".launch-speakpipe-app-icon").click(function(){var a=G;var b=
2==a.siteTypeId?a.siteName:a.publicToken,c=v.getParameterByName("rf");b="speakpipe://"+b+"?vt="+a.visitorToken+"&rf="+encodeURIComponent(c);a.parentMsgId&&a.toEmail&&(b+="&siteid="+encodeURIComponent(a.siteId),b+="&parentmsg="+encodeURIComponent(a.parentMsgId),b+="&toemail="+encodeURIComponent(a.toEmail),a=a.fromUser)&&(a.name&&(b+="&username="+encodeURIComponent(a.name)),a.email&&(b+="&useremail="+encodeURIComponent(a.email)));a=b;R.info("start_ios_app");window.open(a);return!1});p(".appstore-badge-btn").click(function(){R.info("appstore_badge");
alert("After installing, return to this page and tap on the Launch button.");d("launch-ios-app");window.open("https://itunes.apple.com/us/app/speakpipe/id602749650?mt=8&amp;uo=4");return!1})}var p=null,G=null,ea,da=null,Y=null,L=null,K="general_widget",ja=!1,ma=!1,S="start-recording",na,R,ia=!1;return{init:function(a,b,c,f,e,g){ea=c.html5Recorder;p=a;G=b;R=g;na=e;K=f;fa(c);(S=u(e))||(S="start-recording");G.mainPage&&(S=G.mainPage);(a=v.readCookie("dbg_widget_start_page"))&&(S=a);"standalone"!==v.getParameterByName("mode")||
"start-recording"!=S||"ios"==e||v.isBrowser("safari")?d(S):($("#chrome-mic-permission-page").css("margin","140px 10px 0"),aa());e=b.maxDuration;e%60?($(".max-duration-value").text(e),$(".max-duration-units").text("seconds")):($(".max-duration-value").text(e/60),$(".max-duration-units").text("minutes"));e="Send a voice message";a="";if("outbox_widget"==K)e="Create a new audio recording",a="Recording can be saved in your library or sent to email.";else if("free_recorder"==K)e="Enregistreur audio";
else if("simple_widget"==K)e=(a=b.dialog.titleText)?a:"Record audio",a=b.dialog.welcomeMsg;else if(b.toEmail&&b.parentMsgId)e="Reply to the message",a="Send a voice message<br>to "+b.toEmail;else if(b.parentMsgId)e="Reply to the message";else{if(a=b.dialog.titleText)e=a;else if(a=b.dialog.displayName?b.dialog.displayName:1<b.siteTypeId?b.siteName:v.getWebsiteDomain(!0))2!=b.siteTypeId&&(a=v.truncStr(a,27)),e="Send a voice message<br>to "+('<span id="sp-recipient-name">'+a+"</span>");a=b.dialog.welcomeMsg}$("#start-recording-page .widget-page-title").html(e);
$("#ios-app-page .widget-page-title").html(e);$("#android-recorder-page .widget-page-title").html(e);p("#start-recording-page .dlg-msg").html(a);b.parentMsgId||"general_widget"!==K&&"simple_widget"!=K||((e=b.dialog.customCSS)&&$("head").append('<style type="text/css">'+e+"</style>"),(e=b.dialog.thankyouMsg)&&$("#thankyou-page .dlg-msg").html(e));b.isDemo&&$(".demo-tip").show();"free_recorder"==K&&($("#send-recording-page .widget-page-title").text("Save recording on server"),$("#send-recording-page #rc-send-msg").text("Save"),
b.dialog.nameRequired=!1,b.dialog.emailRequired=!1,$("#send-recording-page #-speakpipe-record-author-email").hide(),$("#send-recording-page .section-label").text("Enter your name"));!b.optin.enabled||G.fromUser&&G.fromUser.isSiteOwner||(e=$("#subscribe-email-field #subscribe-email-checkbox"),e.prop("checked",b.optin.defaultValue),e.attr("title",b.optin.shortMsg),$("#subscribe-email-field #subscribe-email-label").text(b.optin.shortMsg),$("#subscribe-email-field").show());b.dialog.isFreePlan?$(".widget-powered-by span").text("Free voicemail widget by"):
b.dialog.whiteLabel&&$(".widget-powered-by").hide();b.dialog.partnerLink&&($(".widget-powered-by a").attr("href",b.dialog.partnerLink),$("#speakpipe-link").attr("href",b.dialog.partnerLink));A.init(jQuery,b);m(b);"outbox_widget"===K?(G.recordingTypeCode="library_rec",C("library_rec"),H("library_rec"),$(".cancel-email-btn").hide()):C();b.isProduction&&($("#start_recording_page #audio-file-upload-form").hide(),$("#ios-app-page #audio-file-upload-form").hide());b=$(".rec-wave-container");e=$("#rec-wave");
e.attr("width",b.width());e.attr("height",b.height());la.init();window.speakpipeStartRecord=aa},showPage:d,setAppType:function(a){K=a}}}(),V=function(){function e(){var a=c.getDataSize?c.getDataSize():null;return 0===a}function f(a){c.requestData&&c.requestData(a)}function a(a,e){var b=c.getCalculatedDuration();if(!(null!==b&&.6>b/a))return null!==e&&.6>e/a?!1:!0;c!=N||d||(d=!0,f(function(b){b&&0<b.size&&(b=(window.URL||window.webkitURL).createObjectURL(b),O.getDuration(b,function(b){null!==b&&.6>
b/a&&(h=!1)}))}));return d&&h?null!==e&&.6>e/a?!1:!0:!1}var c=null,d=!1,h=!0;return{init:function(a){c=a},reset:function(){d=!1;h=!0},isRecordingProcessValid:function(b,d){1<=b&&e()&&f();return 3<b&&!c.isDataStarted()||5<b&&!a(b,d)||12<b&&e()?!1:!0},getRecordingProcessError:function(b,d){return c.isDataStarted()?e()?"data_empty":a(b,d)?null:"duration_error":"data_not_started"}}}(),sa=function(){function e(){var b=f[a];b.duration=h.duration();b.duration<b.timeout?(a++,a<f.length?(b=f[a].size,h.start(),
c(b,e)):(b=b.size/b.duration,d&&d(b))):(b=b.size/b.duration,d&&d(b))}var f=[{size:11483,timeout:7E3},{size:40658,timeout:2500},{size:164897,timeout:2500},{size:381756,timeout:1500},{size:1234664,timeout:1200}],a=0,c=null,d=null,h={_startTime:0,start:function(){this._startTime=(new Date).getTime()},duration:function(){return(new Date).getTime()-this._startTime}};return{start:function(b,n){a=0;b&&n&&(c=b,d=n,b=f[a].size,h.start(),c(b,e))}}}(),ua=function(){var e={no_sound_from_mic:"No sound from the microphone",
listen_your_msg:"Listen to your recording",no_sound_error:"Please check that your microphone is turned on and ensure the recording volume is high enough. <br> If you are sure that everything is correct, try to restart your browsers (sometimes a computer restart also can help).",too_quiet_warn:"It seems your recording is too quiet. <br> You can listen to it before sending to make sure it sounds good.",listen_msg_warn:"You can listen to your voice message before sending to make sure it sounds good.",
too_loud_warn:"It seems your recording is too loud. <br> You can listen to it before sending to make sure it sounds good.",mic_denied:'You have denied SpeakPipe <br> access to your microphone. <br> In order to record a voice message you need to allow access to your microphone. <p><a href="#" onclick="_speakpipe.showMicAllowHelp(); return false;">How to allow access to the microphone</a> </p>',mic_absent:"Safe Health cannot find a microphone in your system. In order to record a voice message, you need a microphone.",
old_flash:'You have an old version of Flash Player. <br> Please update it, and try again. <p> <a href="http://get.adobe.com/flashplayer/" target="_blank">Download the latest Flash Player</a> </p>'};return{get:function(f){(f=e[f])||(f="str_error");return f}}}(),W=function(){function e(a){var b=[],c;for(c in a)b.push({name:c,value:a[c]});return b}function f(a,b){z.postRequest("/start_upload",{audio_format:"mp3"},function(b){a(b.file_name,b.speedtest_params,b.params,b.creation_date)},b)}function a(a,
b,c){z.postRequest("/confirm_upload",a,b,c)}function c(c,d,e,h,t,m){var g=function(a,b,d){c.uploadAudio(a.url,a.uploadParams,a.progressCallback,b,d,a.speedTestParams)};var l=b?"https://speakpipe.s3.amazonaws.com/":"https://speakpipe_dev.s3.amazonaws.com/";var k={},r=n;r.execute(function(a,b,c){f(b,c)},k,function(b,e,f,n){k={url:l,speedTestParams:e,uploadParams:f,progressCallback:h};r.execute(g,k,function(){d.filename_key=b;d.creation_date=n;c.updateMsgParams&&c.updateMsgParams(d);r.execute(a,d,t)},
m)})}function d(a,b,c,d,f){var g=n;a.updateMsgParams&&a.updateMsgParams(b);b=e(b);d={url:h+"/api/upload-audio",progressCallback:d,uploadParams:b};c&&c();g.execute(function(b,c,d){a.uploadAudio(b.url,b.uploadParams,b.progressCallback,c,d,[])},d,f)}var h,b,n;return{init:function(a,c){h=a;b=c;n=new qa},uploadAudio:function(a,b,e,f,h,m,u){var g=!1,k=function(a){g||(g=!0,f&&f());h(a)},l=function(){d(a,b,f,k,m)};e&&e();n.init(u,function(){e&&e()});a.isAmazonUpload&&a.isAmazonUpload()?c(a,b,f,k,m,l):d(a,
b,f,h,m)},retryUpload:function(){n.retry()}}}(),v=function(){function e(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(window.location.search);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))}function f(a){if(a)return a=a.toLowerCase(),-1<navigator.userAgent.toLowerCase().search(a)?!0:!1}return{init:function(a,c){_siteSettings=c},log:function(a,c){},getWebsiteDomain:function(a){var c=null,d=e("rf");d&&(c=document.createElement("a"),c.href=
d,(c=c.hostname)&&a&&(c=(a=c)&&0==a.toLowerCase().indexOf("www.")?a.substring(4):a));return c},getParameterByName:e,truncStr:function(a,c){return a?a.substr(0,c-1)+(a.length>c?"&hellip;":""):a},trimStr:function(a){return a.replace(/^\s\s*/,"").replace(/\s\s*$/,"")},strContains:function(a,c,d){d&&(a=a.toLowerCase(),c=c.toLowerCase());return-1!=a.indexOf(c)},strStartsWith:function(a,c){return 0===a.indexOf(c)},checkUA:f,isOS:function(a){switch(a.toLowerCase()){case "ios":return f("iphone")||f("ipad")||
f("ipod");case "android":return f("android");case "windows":return f("windows");case "macos":return f("mac os x")}return!1},isBrowser:function(a){switch(a.toLowerCase()){case "firefox":return f("firefox");case "chrome":return f("chrome")&&!f("edge");case "ie":return f("msie");case "safari":return f("safari")&&!f("chrome")&&!f("chromium")&&!f("edge")}return!1},isiOS11:function(){if(/iP(hone|od|ad)/.test(navigator.platform)){var a=navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);a=[parseInt(a[1],
10),parseInt(a[2],10),parseInt(a[3]||0,10)]}else a=void 0;return!!(a&&11<=a[0])},isInAppBrowser:function(){return f("instagram")||f("fbios")},readCookie:function(a){a+="=";for(var c=document.cookie.split(";"),d=0;d<c.length;d++){for(var e=c[d];" "==e.charAt(0);)e=e.substring(1,e.length);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return null},setCookie:function(a,c){if(a){var d=new Date;d.setDate(d.getDate()+700);document.cookie=a+"="+c+"; expires="+d.toGMTString()+"; path=/"}},randomString:function(a){for(var c=
"",d=0;d<a;d++)c+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return c}}}();$(document).ready(function(){window.Raven?Raven.context(C):C()})})();

